on: [push]

env:
  TEST: "test" 

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: build
        run: | 
          npm install
          npm run build

      - name: Publish to Cloudflare Pages
        id: pages_deploy 
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 1a9df9d4f6cd820cbcd2c8f76e3b445a
          projectName: astro-magenta-motion
          directory: dist

      - name: output
        run: | 
          echo ${{ steps.pages_deploy.outputs.url }}
          echo ${{ steps.pages_deploy.outputs.id }}
          echo $TEST
